name: Monitoramento CVM

on:
  schedule:
    - cron: "0 9,18 * * *" # roda às 9h e 18h UTC todos os dias
  workflow_dispatch:

jobs:
  monitoramento:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas

      - name: Rodar o script
        run: python nome_do_arquivo.py
